[tool.ruff]
exclude = ["test/lib/python/*"]
extend-select = [
    "S",  # Bandit
    "E9",
    "F63",
    "F7",
    "F82",
    "I",
]
ignore = [
    "E402", # TODO: enable
    "E711", # TODO: enable
    "E712", # TODO: enable
    "E721", # TODO: enable
    "S101", # TODO: enable
    "S110", # TODO: enable
    "S324", # TODO: enable
]
line-length = 167

[tool.ruff.per-file-ignores]
"{test,tests,examples}/**/*.py" = [
    "E741",
    "F401",
    "F811",
    "F841",
    "I",
    "S",
]
